name: Build Release Zips

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install production dependencies
      - name: Install Production Dependencies
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            pwsh ./scripts/build-pack.ps1
          else
            bash ./scripts/build-pack-mac.sh
          fi

      # Upload Windows ZIP
      - name: Upload ZIP
        if: matrix.os == 'windows-latest'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/com.ae.discordrpc-windows-${{ github.ref_name }}.zip
          asset_name: com.ae.discordrpc-windows-${{ github.ref_name }}.zip
          asset_content_type: application/zip

      # Upload macOS ZIP
      - name: Upload ZIP
        if: matrix.os == 'macos-latest'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/com.ae.discordrpc-mac-${{ github.ref_name }}.zip
          asset_name: com.ae.discordrpc-mac-${{ github.ref_name }}.zip
          asset_content_type: application/zip