name: Build Release Zips

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install production dependencies
      - name: Install Production Dependencies
        run: npm ci --prefix com.ae.discordrpc --production

      # Run the build script
      - name: Run Build Script
        run: pwsh ./scripts/build-pack.ps1

      # Upload Windows ZIP
      - name: Upload Windows ZIP
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/com.ae.discordrpc-windows-v${{ github.ref_name }}.zip
          asset_name: com.ae.discordrpc-windows-v${{ github.ref_name }}.zip
          asset_content_type: application/zip

      # Upload macOS ZIP
      - name: Upload macOS ZIP
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/com.ae.discordrpc-mac-v${{ github.ref_name }}.zip
          asset_name: com.ae.discordrpc-mac-v${{ github.ref_name }}.zip
          asset_content_type: application/zip

      # Upload Windows checksum
      - name: Upload Windows Checksum
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/com.ae.discordrpc-windows-v${{ github.ref_name }}.zip.sha256
          asset_name: com.ae.discordrpc-windows-v${{ github.ref_name }}.zip.sha256
          asset_content_type: text/plain

      # Upload macOS checksum
      - name: Upload macOS Checksum
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/com.ae.discordrpc-mac-v${{ github.ref_name }}.zip.sha256
          asset_name: com.ae.discordrpc-mac-v${{ github.ref_name }}.zip.sha256
          asset_content_type: text/plain