name: Build Release Zips

on:
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Build and Package (Windows)
        shell: pwsh
        run: ./scripts/build-pack.ps1
      - name: Upload ZIP as Release Asset (Windows)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/com.ae.discordrpc-windows-v${{ github.ref_name }}.zip
          asset_name: com.ae.discordrpc-windows-v${{ github.ref_name }}.zip
          asset_content_type: application/zip

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Make build-pack-mac.sh executable
        run: chmod +x ./scripts/build-pack-mac.sh
      - name: Build and Package (macOS)
        shell: bash
        run: ./scripts/build-pack-mac.sh
      - name: Upload ZIP as Release Asset (macOS)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/com.ae.discordrpc-mac-v${{ github.ref_name }}.zip
          asset_name: com.ae.discordrpc-mac-v${{ github.ref_name }}.zip
          asset_content_type: application/zip